[package]
name = "css"
version = "0.0.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
readme = "README.md"
description = "Css package"

[lib]
path = "src/lib.rs"


[dependencies]
berlin_core.workspace = true
lightningcss = "1.0.0-alpha.40"
