[package]
name = "markdown"
version = "0.0.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
readme = "README.md"
description = "Markdown package"

[lib]
path = "src/lib.rs"

[dependencies]
serde.workspace = true
pest.workspace = true
pest_derive.workspace = true

berlin_document.workspace = true
sha2.workspace = true
anyhow.workspace = true
comrak.workspace = true
serde-saphyr.workspace = true
slugify.workspace = true
tera.workspace = true
thiserror.workspace = true
url.workspace = true

[dev-dependencies]
tempfile.workspace = true
