[package]
name = "berlin"
version = "0.1.0"
authors.workspace = true
default-run = "bln"
edition.workspace = true
license.workspace = true
repository.workspace = true

[[bin]]
name = "bln"
path = "main.rs"
doc = false

[dependencies]
serde.workspace = true
markdown.workspace = true
berlin_document.workspace = true
berlin_document_html.workspace = true
berlin_document_linkedin.workspace = true
berlin_content.workspace = true
berlin_core.workspace = true
berlin_pipeline_dsl = { path = "../crates/pipeline-dsl", version = "0.0.0" }
anyhow.workspace = true
clap.workspace = true
csv.workspace = true
env_logger.workspace = true
glob.workspace = true
log.workspace = true
lightningcss.workspace = true
notify.workspace = true
serde_json.workspace = true
sha2.workspace = true
slugify.workspace = true
tera.workspace = true
termcolor.workspace = true
tempfile.workspace = true
tokio.workspace = true
url.workspace = true
warp.workspace = true

[dev-dependencies]
tempfile.workspace = true
