[package]
name = "berlin"
version = "0.1.0"
authors.workspace = true
default-run = "bln"
edition.workspace = true
license.workspace = true
repository.workspace = true

[[bin]]
name = "bln"
path = "main.rs"
doc = false


[dependencies]
atty.workspace = true
berlin_core.workspace = true
berlin_runtime.workspace = true
csv.workspace = true
fnmatch-regex = "0.2.0"
futures = { version = "0.3.16" }
lazy_static = "1.4"
lightningcss.workspace = true
log = { workspace = true, features = ["serde"] }
notify.workspace = true
once_cell.workspace = true
percent-encoding.workspace = true
regex.workspace = true
serde.workspace = true
serde_json = "1.0"
slugify = "0.1.0"
tera.workspace = true
tokio.workspace = true
tokio-util.workspace = true

clap = "4.1"
env_logger = "=0.10"
glob = "0.3.1"

[dev-dependencies]
test_util.workspace = true
