[package]
name = "test_util"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
publish = false
repository.workspace = true


[dependencies]
anyhow.workspace = true
once_cell.workspace = true
serde.workspace = true
toml.workspace = true
