[package]
name = "test_util"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
publish = false
repository.workspace = true

[lib]
doctest = false

[dependencies]
