[package]
name = "berlin_document_html"
version = "0.0.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "HTML projection for Berlin semantic documents"

[lib]
path = "lib.rs"

[dependencies]
berlin_document.workspace = true
comrak.workspace = true
sha2.workspace = true

[dev-dependencies]
markdown.workspace = true
