[package]
name = "berlin_document_html"
version = "0.0.0"
authors.workspace = true
edition.workspace = true
license-file.workspace = true
repository.workspace = true
description = "HTML projection for Berlin semantic documents"

[lib]
path = "lib.rs"

[dependencies]
berlin_document.workspace = true
comrak.workspace = true
sha2.workspace = true
serde_json.workspace = true
syntect = { version = "5.3.0", default-features = false, features = ["default-syntaxes", "default-themes", "html"] }

[dev-dependencies]
markdown.workspace = true
