[package]
name = "errors"
version = "0.0.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
readme = "README.md"
repository.workspace = true
description = "Error crate for Berlin"

[lib]
path = "src/lib.rs"

[dependencies]
anyhow = "1.0"
